In [15]:
import pandas as pd

In [16]:
data=pd.read_csv('IRIS.csv')
print(data)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [18]:
data['date_time']=pd.to_datetime(data["sepal_length"])
data.set_index('date_time',inplace=True)
resampled_data = data.resample('M').sum()
print(resampled_data)


            sepal_length  sepal_width  petal_length  petal_width
date_time                                                       
1970-01-31         876.5        458.1         563.8        179.8


In [23]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print("sum:",np.sum(arr))
print("MAX:",np.max(arr))
print("MEAN:",np.mean(arr))
print("MIN:",np.min(arr))

[1 2 3 4 5 6]
sum: 21
MAX: 6
MEAN: 3.5
MIN: 1


In [25]:
reshape_arr=arr.reshape(2,3)
print(reshape_arr)

[[1 2 3]
 [4 5 6]]


In [30]:
arr=np.random.random((3,3))
print(arr)

[[0.14241669 0.13927825 0.44474012]
 [0.56402136 0.48411338 0.64984777]
 [0.98077723 0.94133365 0.04815433]]


In [34]:
arr1=np.array([4,5,6,7,8,9])
arr2=np.array([2,3,4,7,8,9])
result= arr1+arr2
print(result)

[ 6  8 10 14 16 18]


In [42]:
#2d array
arr=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr)
#to flatten in single dimension
one=arr.flatten()
print(one)

[[1 2 3]
 [3 4 5]
 [5 6 7]]
[1 2 3 3 4 5 5 6 7]


In [45]:
#to find sum along axis
sum_rows=np.sum(arr,axis=0)
#sum along columns
sum_column=np.sum(arr,axis=1)
print(sum_rows)
print(sum_column)

[ 9 12 15]
[ 6 12 18]


In [48]:
#indexing
print(arr[1])
#boolean masking
mask=arr>2
filter=arr[mask]
print(filter)

[3 4 5]
[3 3 4 5 5 6 7]


In [52]:
#unique element
uniques =np.unique(arr)
print(uniques)
#count
counts=np.bincount(one)
print(counts)

[1 2 3 4 5 6 7]


ValueError: object too deep for desired array